name = "prometheus-repl"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Enable workers.dev URL for testing
workers_dev = true

routes = [
  { pattern = "prometheus.entrained.ai", custom_domain = true, zone_name = "entrained.ai" }
]

[vars]
PROMETHEUS_EDGE = "https://prometheus-edge.divine-cell-b9ef.workers.dev"
